### ISSUE TITLE
Shorts are shown on the Subscriptions page

### ISSUE THREAD

**Issue by oren0** [ProbablyRaging/hide-youtube-shorts#6]
I have enabled the extension and it was previously working. I still see Shorts on the Subscription page.
![image](https://user-images.githubusercontent.com/24426696/231632221-55e19002-a189-47bc-b764-b261d8f2fa65.png)

You can see 3 shorts shown on the attached screenshot along with the fact that the extension is enabled and that hiding shorts on the subscription page is turned on.

**Comment by zevnda** [comment]
Thank you for providing that screenshot.

May I ask what browser you are using, and have you tried using the extension on a different browser (such as Chrome, Edge, Vivaldi) to see if the issue occurs there too?

Are you using any other extensions that might be conflicting with HYS? Can you try disabling all extensions except for HYS and see if that makes a difference?

As of right now I am unable to reproduce this issue on any of the browsers previously mentioned.

**Comment by oren0** [comment]
This is Chrome. I tried disabling a few other YouTube-specific extensions but it didn't change anything.

**Comment by zevnda** [comment]
May sound trivial, but can you please try uninstalling the extension and then re-installing it from the Chrome Web Store.

**Comment by oren0** [comment]
Done. Didn't fix it.

**Comment by zevnda** [comment]
Sorry, but after testing it on multiple different devices and browsers, I still can't reproduce this issue. As you are the first and only person to report having this issue I can only assume that the issues is related to your system alone at this time.

If you could open the Chrome dev tools window (F12) before visiting the Subscriptions page, and monitor the console output to see if any errors are shown, that would be helpful.

I'll leave this issue open for now to see if anyone else comes forward with the same issue, and hopefully some steps to help me reproduce it. If you are able to provide any further information, feel free to let me know.

**Comment by miltonseco** [comment]
This is also happening to me since Youtube's subscription page revamp a couple of days ago. I looked at the console to check for any javascript errors when loading the page but I can't seen any related to the extension. Maybe this is a slow rollout and not all users have the new subscription page layout.

**Comment by zevnda** [comment]
If YouTube have changed the format of their page recently, that would definitely cause some issues. I've not had these changes rollout to any of my accounts yet. I'll see if I can find someone with an account that has these changes to let me do some testing and I'll update the extension as soon as I can.

Just to confirm, you're not referring to the new UI changes with the rounded corners and such? You're talking about changes after those UI changes?

Thanks for the heads up!

**Comment by zevnda** [comment]
If anyone can upload a file of the entire HTML of the subscriptions page with these new changes, that would be great. The subscriptions page will need to have shorts elements visible at the time

**Comment by miltonseco** [comment]
Yes, there are changes to the UI. It appears that the node name for the videos (on a grid) is now 'ytd-rich-item-renderer' instead of 'YTD-GRID-VIDEO-RENDERER'. Find attached the new HTML of the page (had to change file extension to upload)
Edit: add to reupload the file [subs.txt](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11222478/subs.txt)

**Comment by zevnda** [comment]
Thanks, appreciate it. I'll take a look at it. I likely won't push an update for these changes until the rollout is a bit more wide spread, just incase it is a only a treatment and not a definitive change

**Comment by zevnda** [comment]
@oren0 @miltonseco It would appear that YouTube has ended treatments for this new UI and reverted back to the previous UI. Can you confirm if you're still experiencing this issue?

**Comment by oren0** [comment]
New UI is still there for me as of right now. Looks slightly different but the Shorts still appear.

![image](https://user-images.githubusercontent.com/24426696/233415462-eb9ed68f-218e-4c2d-85c0-e814a006f401.png)

Over the last few days, sometimes the subscription page loads with big empty blocks where the shorts should be, but other times they're still fully there like this.

**Comment by miltonseco** [comment]
Yeah, I still have the new UI, even after clearing cache, cookies and local storage. Maybe it will just take some time for my UI to revert back. Good news if that's true, I prefer the old UI.

**Comment by deastr** [comment]
I have the same issue. 

![image](https://user-images.githubusercontent.com/18551424/233553408-a9bfe036-1579-4afc-b193-af6d7dcf0a0d.png)

Here's the html from the inspect/elements window. Using Chrome.

[subscriptions.html.txt](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11292710/subscriptions.html.txt)

I'm an extension developer myself, I can do debugging if you need it.

**Comment by zevnda** [comment]
> I have the same issue.
> 
> [image]
> 
> Here's the html from the inspect/elements window. Using Chrome.
> 
> [subscriptions.html.txt](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11292710/subscriptions.html.txt)
> 
> I'm an extension developer myself, I can do debugging if you need it.

Thank you, I appreciate the offer. You're welcome to create a PR if you feel like your changes will fix this issue, I'm currently not able to test myself as all my accounts seem to still be on the old UI, so any PRs are greatly encouraged. However, as I have already mentioned, I likely won't be updating the Chrome WS package until the changes are more widespread. Thanks again

**Comment by miltonseco** [comment]
I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?

**Comment by zevnda** [comment]
> I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?

It is still only a small treatment group of people with the new UI, and as I don't have access to the new UI myself I can't push any fixes for it as I have no way to verify if the fixes even work or not, and that they won't cause issues for people outside of the treatment.

You're welcome to give [this fork](https://github.com/Ice-mourne/hide-youtube-shorts) from #11 a try and see if it works for you. It apparently fixes shorts in the subscription feed.

**Comment by GMB23** [comment]
> > I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?
> 
> It is still only a small treatment group of people with the new UI, and as I don't have access to the new UI myself I can't push any fixes for it as I have no way to verify if the fixes even work or not, and that they won't cause issues for people outside of the treatment.
> 
> You're welcome to give [this fork](https://github.com/Ice-mourne/hide-youtube-shorts) a try and see if it works for you. It apparently fixes shorts in the subscription feed.

That fork worked for me. Thanks

**Comment by miltonseco** [comment]
> > > I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?
> > 
> > 
> > It is still only a small treatment group of people with the new UI, and as I don't have access to the new UI myself I can't push any fixes for it as I have no way to verify if the fixes even work or not, and that they won't cause issues for people outside of the treatment.
> > You're welcome to give [this fork](https://github.com/Ice-mourne/hide-youtube-shorts) a try and see if it works for you. It apparently fixes shorts in the subscription feed.
> 
> That fork worked for me. Thanks

How do I exactly do that? I tried to replace the main.js file from the fork on `C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default\Extensions\aljlkinhomaaahfdojalfmimeidofpih\1.5.0_0\js` but now the extension just says "This extension may have been corrupted." and I can't enable it.

**Comment by jeytee84** [comment]
> > I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?
> 
> It is still only a small treatment group of people with the new UI, and as I don't have access to the new UI myself I can't push any fixes for it as I have no way to verify if the fixes even work or not, and that they won't cause issues for people outside of the treatment.
> 
> You're welcome to give [this fork](https://github.com/Ice-mourne/hide-youtube-shorts) from #11 a try and see if it works for you. It apparently fixes shorts in the subscription feed.

While it does hide the shorts, the empty spaces are left behind. Right now it does the same as [this uBlock filter](https://letsblock.it/filters/youtube-shorts)

**Comment by zevnda** [comment]
> > > I still have this issue with the new UI, doesn't seem they are rolling it back. Can you push a version that also addresses the new UI?
> > 
> > 
> > It is still only a small treatment group of people with the new UI, and as I don't have access to the new UI myself I can't push any fixes for it as I have no way to verify if the fixes even work or not, and that they won't cause issues for people outside of the treatment.
> > You're welcome to give [this fork](https://github.com/Ice-mourne/hide-youtube-shorts) from #11 a try and see if it works for you. It apparently fixes shorts in the subscription feed.
> 
> While it does hide the shorts, the empty spaces are left behind. Right now it does the same as [this uBlock filter](https://letsblock.it/filters/youtube-shorts)

Thanks for the feedback. The owner of that fork may wish to update it if they like, I can't as it isn't my repo. I am still waiting to be able to test the new UI if it ever actually gets fully released, but as of now it still seems to be a small treatment group

**Comment by miltonseco** [comment]
Finally, after almost 2 months, my UI is back to the old one and your extension works perfectly again :)

**Comment by zevnda** [comment]
> Finally, after almost 2 months, my UI is back to the old one and your extension works perfectly again :)

Nice! That is good news, hopefully other people's accounts start slowly going back to the old UI as well.

**Comment by wiretail** [comment]
Just as a data point, mine was fine through until today, when shorts started showing in the sub feed with both this/store version and the fork mentioned.  Guessing they are rotating the tests vs being done.  (Not complaining, and will look at making a new fork/example if I'm able.)

**Comment by zevnda** [comment]
Fixed in 1.6.1 with [d8eda0e](https://github.com/ProbablyRaging/hide-youtube-shorts/commit/d8eda0e0b488fd0d5d2f3ba65244bc0e6df7acd6)

You can download the .zip from this repo and load the unpacked version or give it a couple of days to go live on CWS. 

Feel free to open a new issue if you have any more problems with the new UI

**Comment by jeytee84** [comment]
Tested 1.6.1 unpacked, mentioned problem persist for me.

> While it does hide the shorts, the empty spaces are left behind. Right now it does the same as [this uBlock filter](https://letsblock.it/filters/youtube-shorts)

**Comment by zevnda** [comment]
> Tested 1.6.1 unpacked, mentioned problem persist for me.
> 
> > While it does hide the shorts, the empty spaces are left behind. Right now it does the same as [this uBlock filter](https://letsblock.it/filters/youtube-shorts)

Yeah so unfortunately it looks like this is going to be unavoidable.

The way the new UI renders content on that page is in seperate grids. Each grid consists of only a 4x1 row (pictured below). Previously, IIRC, it used to just render them all in one big flex box so when you removed one video it would just fill the gap. But with the new UI there are only 4 videos in the row so if you remove one, there is no other video to fill the gap.

If you remove one video from the start of the row, the other 3 videos will shift over as you'd expect though.

I was contemplating adding a custom div that replicated the style of the removed div, just to fill that gap, but I though that might be even more annoying to people. I might could add that as a togglable option or something though. I'm still trying different methods to see what will work best.

Thanks for letting me know.

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/24839609/7d976ce7-42c6-4ed9-b955-526611b6c936)

**Comment by zevnda** [comment]
I was thinking of doing something like this to fill those gaps? Have it be a togglable option. 

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/24839609/3a5bd511-fe3e-4404-a95b-a9fd28e3e2e6)

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/24839609/8f571a23-602d-484e-83a5-5753ab9d43d4)

**Comment by zevnda** [comment]
> Tested 1.6.1 unpacked, mentioned problem persist for me.
> 
> > While it does hide the shorts, the empty spaces are left behind. Right now it does the same as [this uBlock filter](https://letsblock.it/filters/youtube-shorts)

The issue with empty spaces/placeholder images is fixed in 1.6.7 with 56a664e847090713a9375ee7774f41e158f9d21b. Credit to HorsyNox for supplying the fix.

Just wanted to update this issue as it has had the most attention over the course of this whole ordeal lol.

**Comment by jeytee84** [comment]
Works perfectly! Thank you very much for all you guys' hard work!

**Comment by wiretail** [comment]
Just noting this in case it's useful for anyone still having issues: If you are running the "Shorts Deflector" extension, it will now conflict and break the Shorts hiding in several places.  (But Shorts Deflector or similar isn't needed anymore, as this extension now includes "play shorts as normal video" since 1.6.0)

It appears to still run fine with no issues alongside many of the other major extensions, such as Improve YouTube, Adblock for Youtube, SponsorBlock, etc.
